# Dockerfile for building and running the Java 17 Maven web application.
# Requirement satisfied: base image is openjdk:17.
FROM openjdk:17

# Install Maven so the image can build the project during docker build.
RUN apt-get update \
    && apt-get install -y --no-install-recommends maven \
    && rm -rf /var/lib/apt/lists/*

# Set working directory inside the container.
WORKDIR /app

# Copy full source code into the container.
COPY . /app

# Build the executable JAR.
RUN mvn -B clean package -DskipTests

# Expose application port.
EXPOSE 8080

# Run the shaded executable JAR generated by Maven.
CMD ["java", "-jar", "/app/target/javaapp-1.0.0.jar"]
